"""
Jobs router — upload media, get plates in the database.

This is the endpoint the demo drives: a video goes in, a job id comes back
immediately, a WebSocket streams progress while the pipeline runs, and the
plates land in `vehicle_events` for the same camera the operator picked.

Two things worth explaining:

**`source_path` exists so the demo does not have to upload 180 MB.** The test
footage already sits on the machine running the API. Re-uploading it through
multipart to process it would add minutes to a live demo for no benefit, so a
path can be passed instead — restricted to a small allowlist of directories,
because an unrestricted server-side path parameter is a file-read primitive
handed to whoever can reach the API.

**Nothing here returns a traceback.** Every handler maps failures onto an
HTTPException with a sentence an operator can act on. The traceback still goes
to the server log, where it is useful.
"""
from __future__ import annotations

import asyncio
import re
import uuid
from pathlib import Path

from fastapi import (
    APIRouter,
    File,
    Form,
    HTTPException,
    UploadFile,
    WebSocket,
    WebSocketDisconnect,
)
from fastapi.responses import FileResponse

from backend.services import compute_monitor, dataset_service, video_job_service
from backend.services.video_job_service import TERMINAL_STATES

_rest = APIRouter(prefix="/jobs", tags=["Jobs"])

VIDEO_EXTENSIONS = {".mp4", ".mov", ".avi", ".mkv", ".m4v", ".webm", ".mpg", ".mpeg"}
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"}

# 512 MB. The largest piece of test footage is 180 MB, and a cap exists so a
# malformed or hostile upload cannot fill the disk that the SQLite database
# lives on.
MAX_VIDEO_BYTES = 512 * 1024 * 1024
MAX_IMAGE_BYTES = 32 * 1024 * 1024

# Read the upload in chunks rather than `await file.read()`: a single read
# materializes the whole 180 MB video in RAM before a single byte is written.
CHUNK = 4 * 1024 * 1024

# Directories a client may reference by path. Anything outside these is
# refused, so `source_path` cannot be used to read /etc/passwd or a .env file.
ALLOWED_SOURCE_ROOTS = [
    video_job_service.UPLOAD_DIR,
    Path("/Users/aarushsharma/Documents/SIH/archive"),
    Path("/Users/aarushsharma/Documents/SIH/services/alpr"),
]

_SAFE_NAME = re.compile(r"[^A-Za-z0-9._-]+")

# ── ready-made demo datasets ─────────────────────────────────────────────────
# Generated by scripts/generate_mumbai_sample.py, which anchors its timestamps
# to "now" at build time — a checked-in file with last year's dates is a demo
# that fails silently, because every default 24h/7d window would come up empty.
_DEPLOYMENTS_DIR = Path(__file__).resolve().parent.parent.parent / "deployments"

_MUMBAI_REGEN = ".venv/bin/python scripts/generate_mumbai_sample.py"

_SAMPLE_DATASETS: dict[str, dict[str, str]] = {
    "mumbai-week": {
        "label": "Mumbai — one week",
        "description": (
            "41 real junctions across Mumbai's arterial network; ~31,000 sightings of "
            "~750 vehicles over 7 days, with commuter peaks, a congestion curve, three "
            "planted watchlist plates and a set of habitual speeders."
        ),
        "relative": "mumbai/mumbai_week.json",
        "filename": "mumbai_week.json",
        "media_type": "application/json",
        "regenerate": _MUMBAI_REGEN,
    },
    "mumbai-cameras-csv": {
        "label": "Mumbai — cameras (CSV)",
        "description": "The camera artefact alone, as CSV.",
        "relative": "mumbai/mumbai_cameras.csv",
        "filename": "mumbai_cameras.csv",
        "media_type": "text/csv",
        "regenerate": _MUMBAI_REGEN,
    },
    "mumbai-events-csv": {
        "label": "Mumbai — events (CSV)",
        "description": "The event artefact alone, as CSV.",
        "relative": "mumbai/mumbai_events.csv",
        "filename": "mumbai_events.csv",
        "media_type": "text/csv",
        "regenerate": _MUMBAI_REGEN,
    },
}


def _sample_path(key: str) -> Path | None:
    """Resolve a sample to a real file, or None if it has not been generated."""
    spec = _SAMPLE_DATASETS.get(key)
    if spec is None:
        return None
    path = (_DEPLOYMENTS_DIR / spec["relative"]).resolve()
    # Confine to deployments/ even though `key` comes from a fixed dict: the
    # check costs nothing and survives someone later making the key dynamic.
    try:
        path.relative_to(_DEPLOYMENTS_DIR.resolve())
    except ValueError:
        return None
    return path if path.is_file() else None


# ── helpers ──────────────────────────────────────────────────────────────────

def _safe_suffix(filename: str | None, allowed: set[str], what: str) -> str:
    suffix = Path(filename or "").suffix.lower()
    if suffix not in allowed:
        raise HTTPException(
            status_code=400,
            detail=(
                f"Unsupported {what} format '{suffix or filename or 'unknown'}'. "
                f"Allowed: {', '.join(sorted(allowed))}"
            ),
        )
    return suffix


async def _save_upload(file: UploadFile, allowed: set[str], max_bytes: int, what: str) -> Path:
    """Stream an upload to disk, enforcing the size cap as it goes."""
    suffix = _safe_suffix(file.filename, allowed, what)

    video_job_service.UPLOAD_DIR.mkdir(parents=True, exist_ok=True)
    # The client's filename is kept for readability but sanitized and prefixed
    # with a uuid, so two uploads of "video.mp4" cannot overwrite each other and
    # a crafted name cannot escape the upload directory.
    stem = _SAFE_NAME.sub("_", Path(file.filename or "upload").stem)[:60] or "upload"
    target = video_job_service.UPLOAD_DIR / f"{uuid.uuid4().hex[:12]}_{stem}{suffix}"

    written = 0
    try:
        with target.open("wb") as out:
            while True:
                chunk = await file.read(CHUNK)
                if not chunk:
                    break
                written += len(chunk)
                if written > max_bytes:
                    raise HTTPException(
                        status_code=413,
                        detail=(
                            f"{what.capitalize()} exceeds the "
                            f"{max_bytes // (1024 * 1024)} MB limit. "
                            "Pass source_path instead to process a file already on the server."
                        ),
                    )
                out.write(chunk)
    except HTTPException:
        target.unlink(missing_ok=True)
        raise
    except Exception as exc:
        target.unlink(missing_ok=True)
        raise HTTPException(status_code=500, detail=f"Could not save upload: {exc}") from exc

    if written == 0:
        target.unlink(missing_ok=True)
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    return target


def _resolve_source_path(source_path: str, allowed: set[str], what: str) -> Path:
    """Validate a server-side path against the allowlist."""
    try:
        path = Path(source_path).expanduser().resolve(strict=True)
    except (OSError, RuntimeError):
        raise HTTPException(status_code=400, detail=f"source_path not found: {source_path}") from None

    if not path.is_file():
        raise HTTPException(status_code=400, detail=f"source_path is not a file: {path}")

    roots = [r.resolve() for r in ALLOWED_SOURCE_ROOTS if r.exists()]
    if not any(path.is_relative_to(root) for root in roots):
        raise HTTPException(
            status_code=403,
            detail=(
                "source_path must live under an allowed directory: "
                + ", ".join(str(r) for r in roots)
            ),
        )

    if path.suffix.lower() not in allowed:
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported {what} format '{path.suffix}'. Allowed: {', '.join(sorted(allowed))}",
        )
    return path


def _submit_or_400(fn, **kwargs) -> str:
    """Turn the job runner's validation errors into clean 4xx responses."""
    try:
        return fn(**kwargs)
    except FileNotFoundError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except (ValueError, KeyError) as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    except Exception as exc:  # model load failure, bad weights path, ...
        raise HTTPException(
            status_code=500, detail=f"Could not start job: {type(exc).__name__}: {exc}"
        ) from exc


# ── submission ───────────────────────────────────────────────────────────────

@_rest.post("/video", status_code=202)
async def create_video_job(
    camera_id: str = Form(...),
    file: UploadFile | None = File(default=None),
    source_path: str | None = Form(default=None),
    ocr_every: int = Form(default=3),
    min_reads: int = Form(default=2),
    max_frames: int | None = Form(default=None),
    region: str | None = Form(default=None),
    sandbox: bool = Form(default=False),
):
    """
    Submit a video for plate detection + database ingestion.

    Provide either a multipart `file` upload, or `source_path` pointing at a
    video already on the server (much faster for large local footage).
    Returns 202 with a job id — poll GET /jobs/{job_id} or subscribe to
    WS /ws/jobs/{job_id}.
    """
    if file is None and not source_path:
        raise HTTPException(
            status_code=400, detail="Provide either a 'file' upload or a 'source_path'."
        )
    if file is not None and source_path:
        raise HTTPException(
            status_code=400, detail="Provide 'file' or 'source_path', not both."
        )

    if source_path:
        path = _resolve_source_path(source_path, VIDEO_EXTENSIONS, "video")
    else:
        path = await _save_upload(file, VIDEO_EXTENSIONS, MAX_VIDEO_BYTES, "video")

    job_id = _submit_or_400(
        video_job_service.submit_video_job,
        file_path=path,
        camera_id=camera_id,
        ocr_every=ocr_every,
        min_reads=min_reads,
        max_frames=max_frames,
        region=region,
        sandbox=sandbox,
    )
    return {
        "job_id": job_id,
        "state": "QUEUED",
        "camera_id": camera_id,
        "source": path.name,
        "sandbox": sandbox,
        "poll": f"/jobs/{job_id}",
        "stream": f"/ws/jobs/{job_id}",
    }


@_rest.post("/image", status_code=202)
async def create_image_job(
    camera_id: str = Form(...),
    file: UploadFile | None = File(default=None),
    source_path: str | None = Form(default=None),
    region: str | None = Form(default=None),
    sandbox: bool = Form(default=False),
):
    """
    Submit a single photo. Uses still-image settings (no cross-frame voting),
    so accuracy is raw OCR accuracy rather than the voted figure.
    """
    if file is None and not source_path:
        raise HTTPException(
            status_code=400, detail="Provide either a 'file' upload or a 'source_path'."
        )
    if file is not None and source_path:
        raise HTTPException(
            status_code=400, detail="Provide 'file' or 'source_path', not both."
        )

    if source_path:
        path = _resolve_source_path(source_path, IMAGE_EXTENSIONS, "image")
    else:
        path = await _save_upload(file, IMAGE_EXTENSIONS, MAX_IMAGE_BYTES, "image")

    job_id = _submit_or_400(
        video_job_service.submit_image_job,
        file_path=path,
        camera_id=camera_id,
        region=region,
        sandbox=sandbox,
    )
    return {
        "job_id": job_id,
        "state": "QUEUED",
        "camera_id": camera_id,
        "source": path.name,
        "sandbox": sandbox,
        "poll": f"/jobs/{job_id}",
    }


# ── city dataset ─────────────────────────────────────────────────────────────
# "Bring your own city": upload a camera network and/or its plate sightings and
# have the whole platform come up on that data. Declared before /{job_id} so
# neither "dataset" nor "system" can be captured as a job id.

@_rest.get("/dataset/schema", tags=["Jobs"])
def dataset_schema():
    """
    The exact format the dataset endpoint accepts — machine-readable.

    This is the source of truth the sandbox page renders its field table and
    its downloadable templates from, so what is documented cannot drift from
    what the parser enforces. It is also the answer to "what do I send?" for
    anyone driving the API directly.
    """
    return dataset_service.SCHEMA


@_rest.get("/dataset/samples")
def list_dataset_samples():
    """Which ready-made demo datasets this server can hand out."""
    out = []
    for key, spec in _SAMPLE_DATASETS.items():
        path = _sample_path(key)
        out.append({
            "key": key,
            "label": spec["label"],
            "description": spec["description"],
            "filename": spec["filename"],
            "available": path is not None,
            "bytes": path.stat().st_size if path else None,
            "download": f"/jobs/dataset/samples/{key}",
            "regenerate": spec["regenerate"],
        })
    return {"samples": out}


@_rest.get("/dataset/samples/{key}")
def download_dataset_sample(key: str):
    """
    Download a ready-made demo dataset in the exact format /jobs/dataset accepts.

    Serving these from the API rather than shipping them in the page keeps one
    copy on disk: the same file a demonstrator uploads is the file the
    generator wrote, so "it validated for me" means something.
    """
    spec = _SAMPLE_DATASETS.get(key)
    if spec is None:
        raise HTTPException(
            status_code=404,
            detail=f"Unknown sample '{key}'. Available: {', '.join(_SAMPLE_DATASETS)}.",
        )
    path = _sample_path(key)
    if path is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"{spec['label']} has not been generated on this server yet. "
                f"Run: {spec['regenerate']}"
            ),
        )
    return FileResponse(path, media_type=spec["media_type"], filename=spec["filename"])


@_rest.post("/dataset/validate")
async def validate_dataset(
    file: UploadFile = File(...),
    kind: str = Form(default="auto"),
):
    """
    Parse and validate a dataset without writing anything, anywhere.

    Returns the same per-row error list (`artefact`, `row`, `msg`) the browser
    produces, so a client can show one error widget regardless of which side
    caught the problem.
    """
    parsed = await _read_and_parse_dataset(file, kind)
    summary = parsed.summary()
    summary["warnings"] = summary["warnings"] + await _threaded(_reference_warnings, parsed)
    summary["ingestable"] = not parsed.errors and parsed.rows_parsed > 0
    return summary


@_rest.post("/dataset", status_code=201)
async def ingest_dataset(
    file: UploadFile = File(...),
    kind: str = Form(default="auto"),
    sandbox: bool = Form(default=True),
    deployment: str | None = Form(default=None),
):
    """
    Ingest a city dataset (cameras and/or events) — JSON or CSV.

    `sandbox` defaults to **true**: the rows land in a throwaway database file
    with the production schema, so a stranger's upload can exercise the real
    pipeline without being able to overwrite the live city's cameras. Pass
    `sandbox=false` to load into the operational database.

    A dataset with any row error is refused as a whole (422) rather than
    partially loaded — half a city is worse than none, because every downstream
    trajectory would then be silently missing hops.
    """
    parsed = await _read_and_parse_dataset(file, kind)

    if parsed.errors:
        summary = parsed.summary()
        summary["warnings"] = summary["warnings"] + await _threaded(_reference_warnings, parsed)
        raise HTTPException(
            status_code=422,
            detail={
                "message": (
                    f"{len(parsed.errors)} row(s) do not match the contract; nothing "
                    f"was ingested. See GET /jobs/dataset/schema for the field list."
                ),
                **summary,
            },
        )
    if parsed.rows_parsed == 0:
        raise HTTPException(
            status_code=422,
            detail="The file parsed cleanly but contained no camera or event rows.",
        )

    try:
        result = await _threaded(
            dataset_service.ingest, parsed, sandbox=sandbox, deployment=deployment
        )
    except HTTPException:
        raise
    except Exception as exc:  # noqa: BLE001 — surface a sentence, log the trace
        raise HTTPException(
            status_code=500,
            detail=f"Ingestion failed: {type(exc).__name__}: {exc}",
        ) from exc

    result["warnings"] = await _threaded(_reference_warnings, parsed)
    return result


async def _threaded(fn, *args, **kwargs):
    """Run blocking work off the event loop.

    These handlers are `async def` because reading a multipart upload in chunks
    needs `await`. That makes everything else in them run *on the event loop* —
    and dataset ingestion is a long synchronous stretch of SQLite writes. Called
    directly, a 31k-row upload blocks every other request for its whole
    duration, and if it stalls on a write lock (the simulation clock holds one
    every half second) the entire API stops answering, not just this request.

    `asyncio.to_thread` puts it back where blocking work belongs.
    """
    import functools

    return await asyncio.to_thread(functools.partial(fn, *args, **kwargs))


async def _read_and_parse_dataset(file: UploadFile, kind: str):
    """Shared body of the validate and ingest handlers."""
    if kind not in ("auto", "cameras", "events"):
        raise HTTPException(
            status_code=400,
            detail=f"kind must be 'auto', 'cameras' or 'events', not {kind!r}.",
        )

    # Read in chunks against the cap rather than file.read(): an unbounded read
    # of a hostile upload is a memory-exhaustion primitive.
    limit = dataset_service.MAX_UPLOAD_BYTES
    buffer = bytearray()
    while True:
        chunk = await file.read(CHUNK)
        if not chunk:
            break
        buffer.extend(chunk)
        if len(buffer) > limit:
            raise HTTPException(
                status_code=413,
                detail=f"Dataset exceeds the {limit // (1024 * 1024)} MB limit.",
            )
    if not buffer:
        raise HTTPException(status_code=400, detail="Uploaded file is empty.")

    try:
        return dataset_service.parse_dataset(bytes(buffer), file.filename, kind)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


def _reference_warnings(parsed) -> list[str]:
    """Flag events whose camera_id is defined neither in the file nor in the DB."""
    if not parsed.events:
        return []
    try:
        from backend.database import SessionLocal
        from backend.models.camera import Camera

        session = SessionLocal()
        try:
            dataset_service._set_busy_timeout(session)
            referenced = sorted({e["camera_id"] for e in parsed.events})
            known: set[str] = set()
            for start in range(0, len(referenced), 500):
                chunk = referenced[start:start + 500]
                known |= {
                    row[0] for row in
                    session.query(Camera.camera_id).filter(Camera.camera_id.in_(chunk)).all()
                }
        finally:
            session.close()
    except Exception:
        known = set()
    return dataset_service.check_references(parsed, known)


# ── inspection ───────────────────────────────────────────────────────────────
# Declared before /{job_id} so "system" cannot be captured as a job id.

@_rest.get("/system/compute")
def system_compute():
    """Device info + live process usage, for the dashboard's compute panel."""
    try:
        return compute_monitor.snapshot()
    except Exception as exc:
        raise HTTPException(
            status_code=500, detail=f"Compute telemetry unavailable: {exc}"
        ) from exc


@_rest.get("")
@_rest.get("/")
def list_recent_jobs(limit: int = 25):
    """Recent jobs, newest first, without the full plate lists."""
    limit = max(1, min(limit, video_job_service.MAX_JOBS))
    return {"jobs": video_job_service.list_jobs(limit=limit)}


@_rest.get("/{job_id}")
def read_job(job_id: str):
    """Full status: progress, live counters, pipeline stats, compute summary."""
    job = video_job_service.get_job(job_id)
    if job is None:
        raise HTTPException(
            status_code=404,
            detail=f"Job '{job_id}' not found. Only the last "
            f"{video_job_service.MAX_JOBS} jobs are retained.",
        )
    return job


@_rest.get("/{job_id}/plates")
def read_job_plates(job_id: str):
    """The plates this job found — final rows, plus in-progress votes if running."""
    plates = video_job_service.get_job_plates(job_id)
    if plates is None:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")
    return plates


@_rest.get("/{job_id}/events")
def read_job_events(job_id: str, limit: int = 200):
    """Events a *sandbox* job wrote, read back from its isolated database.

    Non-sandbox jobs write into the main tables, so their events are already
    visible through /events/recent and are not duplicated here.
    """
    job = video_job_service.get_job(job_id)
    if job is None:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")
    if not job.get("sandbox"):
        raise HTTPException(
            status_code=400,
            detail="This job wrote to the main database — use GET /events/recent instead.",
        )
    limit = max(1, min(limit, 1000))
    return {
        "job_id": job_id,
        "events": video_job_service.sandbox_events(job_id, limit=limit),
    }


@_rest.post("/{job_id}/cancel")
def cancel_job(job_id: str):
    """Stop a running job at the next frame; plates read so far are kept."""
    if video_job_service.get_job(job_id) is None:
        raise HTTPException(status_code=404, detail=f"Job '{job_id}' not found.")
    if not video_job_service.cancel_job(job_id):
        raise HTTPException(status_code=409, detail="Job has already finished.")
    return {"job_id": job_id, "cancelling": True}


# ── live progress ────────────────────────────────────────────────────────────
# A second, unprefixed router: the frontend groups every WebSocket under /ws,
# and an APIRouter prefix applies to websocket routes too, so /jobs + /ws
# cannot come from one router. Both are combined into `router` at the bottom so
# backend/main.py still needs exactly one include_router call.
_ws = APIRouter(tags=["Jobs"])


@_ws.websocket("/ws/jobs/{job_id}")
async def stream_job(websocket: WebSocket, job_id: str):
    """Push the job status ~2x/second until it reaches a terminal state.

    Closes itself once the job finishes rather than idling forever: a dashboard
    that leaves a socket open per completed upload accumulates them for the
    length of the demo.
    """
    await websocket.accept()

    job = video_job_service.get_job(job_id)
    if job is None:
        # Accept first, then report — a client that gets a bare handshake
        # rejection has no way to show the user why.
        try:
            await websocket.send_json({"error": f"Job '{job_id}' not found."})
            await websocket.close(code=1008)
        except Exception:
            pass
        return

    try:
        while True:
            job = video_job_service.get_job(job_id)
            if job is None:
                await websocket.send_json({"error": "Job record was evicted."})
                break

            await websocket.send_json(job)
            if job["state"] in TERMINAL_STATES:
                break
            await asyncio.sleep(0.5)
    except (WebSocketDisconnect, asyncio.CancelledError):
        # Normal: the operator navigated away mid-run. Not an error, and it
        # must not take the job down with it.
        return
    except Exception:
        return
    finally:
        try:
            await websocket.close()
        except Exception:
            pass


# The single router backend/main.py includes. Combining here rather than asking
# main.py for two lines keeps the app wiring to one entry per feature.
router = APIRouter()
router.include_router(_rest)
router.include_router(_ws)
