"""TrafficSnapshot ORM model — aggregated traffic metrics per camera window."""
import uuid
from datetime import datetime
from typing import Any

from sqlalchemy import JSON, DateTime, Float, ForeignKey, Integer, String, func
from sqlalchemy.orm import Mapped, mapped_column

from backend.database import Base


class TrafficSnapshot(Base):
    """
    Time-windowed traffic aggregation generated by camera workers or analytics engine.
    Stores density, average speed, peak frame density, class breakdowns, and congestion.
    """
    __tablename__ = "traffic_snapshots"

    snapshot_id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=lambda: str(uuid.uuid4())
    )
    camera_id: Mapped[str] = mapped_column(String(50), ForeignKey("cameras.camera_id"), index=True)
    window_start: Mapped[datetime] = mapped_column(DateTime, index=True)
    window_end: Mapped[datetime] = mapped_column(DateTime)

    vehicle_count: Mapped[int] = mapped_column(Integer, default=0)
    avg_speed: Mapped[float | None] = mapped_column(Float, nullable=True)
    peak_density: Mapped[int] = mapped_column(Integer, default=0)
    class_counts: Mapped[dict[str, Any]] = mapped_column(JSON, default=dict)
    congestion_level: Mapped[str] = mapped_column(String(20), default="LOW")  # LOW, MEDIUM, HIGH

    created_at: Mapped[datetime] = mapped_column(DateTime, server_default=func.now())
